export const routes = Object.freeze({
	ROOT: "/",
	ABOUT: "/about",
	CONTACT: "/contact",
	HOME: "/home",
	LOGIN: "/login",
	ONBOARDING: "/onboarding",
	PRIVACY_POLICY: "/privacy-policy",
	BOARD: "/board",
	SPRINTS: "/sprints",
	CALENDAR: "/calendar",
	PROJECTS: "/projects",
	PROJECT: (id: string) => `/projects/${id}`,
	TASK: (id: string) => `/tasks/${id}`,
	SPRINT: (id: string) => `/sprints/${id}`,
	ERROR: "/500",
	PROFILE: "/profile",
});
